image: python:3.10

stages:
  - build
  - test
  - secure
  - deploy
  - monitor
  - ai_agent

variables:
  MODEL_ACC_THRESHOLD: "0.85"

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

build_job:
  stage: build
  script:
    - echo "ðŸ”§ Building SonicSight project..."
    - python main.py || echo "Skipping camera execution on CI"
  artifacts:
    paths:
      - reports/
    expire_in: 1 week

test_job:
  stage: test
  image: python:3.11
  before_script:
    - apt-get update -y && apt-get install -y libglib2.0-0
    - python --version
    - pip install -r requirements.txt
  script:
    - echo "âœ… Running SonicSight import test (no GUI)..."
    - python -c "from main import main; print('âœ… main.py imported successfully')"


#include:
#  - template: Security/SAST.gitlab-ci.yml

deploy_job:
  stage: deploy
  script:
    - mkdir -p public
    - echo "<h1>SonicSight Build Successful âœ…</h1>" > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main

monitor_job:
  stage: monitor
  script:
    - python metrics_logger.py || echo "Monitoring complete"
  only:
    - schedules

ai_agent_job:
  stage: ai_agent
  script:
    - python ai_agent.py
    - python ai_optimizer.py
  only:
    - main



